class Routes:
    DASHBOARD = "fetch dashboard:get"
    ADDITIONAL_COST = "put additional cost:post"
    FETCH_ADDITIONAL_COST = "get additional cost:get"
    FETCH_DATE_WISE_DATA = "get data wise data:get"
    TRACKER = "fetch tracker:post"
    PINCODE_SKU = "fetch pincode sku:get"
    RTO_DATA = "fetch rto data:get"
    PAYMENT_DATA = "fetch payment data:get"
    CHECK_DEPENDENCIES = "check dependencies:get"
    DATA_GET = "get data:get"
    DATA_PUT = "put data:post"
    DATA_DELETE = "delete data:delete"
    DOWNLOAD_DATA = "download data:get"
    GET_DATA = "download data:get"
